### PR TITLE
Backport elasticsearch fixes

### PR DESCRIPTION
**Pull request by kohaputti**
The first commit shows during indexing if there was an error with indexing a record, as previously it was a silent failure. The second one fixes indexing for records that have hundreds or more items in them.

### CODE REVIEW

**Comment by EreMaijala** [comment]
Looks good to me :+1:

**Comment by johannaraisa** [comment]
Is this error message "[ContentLength] ** Body is longer than max_content_length (104857600), called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/koha/Koha/Koha/SearchEngine/Elasticsearch/Indexer.pm line 135." related to this bug? Do I have to change something from mappings?

**Comment by EreMaijala** [comment]
@johannaraisa Possibly. The old code used to index massive arrays for item fields making it easier to overflow. Alternative, you could try a smaller commit interval with rebuild_elasticsearch.pl.

**Comment by johannaraisa** [comment]
@EreMaijala Seems to be working when commiting in smaller chunks.

**Comment by johannaraisa** [comment]
I got this type of error on details page:

[Request] ** [http://127.0.0.1:9200]-[400] [query_shard_exception] No mapping found for [local-number__sort.phrase] in order to sort on

When changed the sort value of local-number from 0 to 1 it started working.

**Comment by kohaputti** [comment]
@johannaraisa I noticed that now too, I will send a fix for that

**Comment by kohaputti** [comment]
Pull request #133 fixes this issue

**Pull request merged**
