### PR TITLE
Bug 7376 - Transfer limits should be checked at check-in

### PR DESCRIPTION
**Pull request by taskula**
This PR solves issues described in Bug 7376 and in the following Redmine comment

https://tiketti.koha-suomi.fi/issues/3375#note-13

### CODE REVIEW

**Comment by taskula** [comment]
Fixed two bugs:
- Wrong branchname at Transfer is forbidden between [% Branches.GetName( holdingbranch ) %] (item's current library) and <<here>>.
- Only check hold transfer limit when hold is actually found

Btw, regarding hold transfer limits at check-in, [Bug 22330](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=22330) already fixes it. So we can drop patch b29847488640f63f27c739b530de36b7cf580f20 when next upgrading the system. However it is still required to check transfer limits at check-in thus Bug 7376 is still valid and also fixed in this pull request.

**Comment by johannaraisa** [comment]
Is this ok, @kohaputti found some bug?

**Comment by kohaputti** [comment]
I have not tested this yet, maybe we should still keep this pull request open until someone does that.

**Comment by kohaputti** [comment]
We have some libraries that might depend on this buggy behaviour that this pull request fixes so this should go on hold.

**Pull request closed without merging**
