### PR TITLE
KD-4047: fix to swagger array definition

### PR DESCRIPTION
**Pull request by oemta001XAMK**

### CODE REVIEW

**Comment by kivilahtio** [comment]
Hi!
What is the purpose of this fix?

I get this error

```
Error while loading /home/koha/Koha/misc/plack/plack.psgi: Can't load application from file "/home/koha/Koha/api/v1/app.pl": Invalid schema:
/parameters/biblionumbersQueryParam: oneOf failed: Properties not allowed: type, collectionFormat, items. oneOf failed: (Properties not allowed: -type.. Not in enum list: header.) (Properties not allowed: -type.. Not in enum list: formData.) Properties not allowed: -type. (Missing property.. Properties not allowed: -type.. Not in enum list: path.)
/parameters/itemnumbersQueryParam: oneOf failed: Properties not allowed: type, collectionFormat, items. oneOf failed: (Not in enum list: header.. Properties not allowed: -type.) (Not in enum list: formData.. Properties not allowed: -type.) Properties not allowed: -type. (Missing property.. Properties not allowed: -type.. Not in enum list: path.) at /usr/local/share/perl/5.26.1/JSON/Validator/OpenAPI.pm line 28.
```

property "-type" is not part of the OpenAPI 2.0 specification.

**Comment by johannaraisa** [comment]
For some reason the those endpoints didn't accept arrays, there was an error which said "Exepting integer - got array". We tested this here and it seemed to work with that fix.

**Comment by johannaraisa** [comment]
Will revert it and look again.

**Comment by kivilahtio** [comment]
Is this a peculiarity with the OpenAPI module version?
Afaik the version in use should be Mojolicious::Plugin::OpenAPI@1.15

**Pull request merged**
