### PR TITLE
KD-1886: (squashme) Fixed two same case file names Labels.js and labels.js

### PR DESCRIPTION
**Pull request by nugged**
which makes repository (often case) and site (rare case because we're using Ubuntu)
incompatible with case insensitive file systems.

This makes git emitting warnings on a case insensitive file systems
and breaks the repository just out of the box on such system.
This of course not the Ubuntu related case but there's no such errors for example in Koha Community version and generally bad practice.

TL;DR:

  There are two similarly named files in the repo, with different case:

  _koha-tmpl/intranet-tmpl/prog/js/labels.js_ - this file just adds "clicks" events for dom elements
  _koha-tmpl/intranet-tmpl/prog/js/Labels.js_ - this is the module

  them both included in _koha-tmpl/intranet-tmpl/prog/en/modules/labels/oplib-label-create.tt_ file,
  so changing name for "clicks" file to 'labels_clicks.js' should remove this problem and keep all working:

```
<script src="[% interface %]/prog/js/Labels.js"></script>
...
<script src="[% interface %]/prog/js/labels_clicks.js"></script>
```

  instead of old:

```
<script src="[% interface %]/prog/js/Labels.js"></script>
...
<script src="[% interface %]/prog/js/labels.js"></script>
```

### CODE REVIEW

**Comment by johannaraisa** [comment]
This commit caused an error on production "Loading failed for the <script> with source “https://renki.lumme-kirjastot.fi/intranet-tmpl/prog/js/labels_clicks.js”."

**Comment by nugged** [comment]
manually it shows the script contents:
https://renki.lumme-kirjastot.fi/intranet-tmpl/prog/js/labels_clicks.js

image

can be this because of some browser-cached pages/links/contents?

**Comment by johannaraisa** [comment]
Yes, I'm trying to figure out which cache is causing this. I loaded the page with CTRL+F5 and cleared history from browser and still it can't load the script.

**Comment by johannaraisa** [comment]
Had to revert that on production so the old file is available again and it is also giving the same result.

**Comment by nugged** [comment]
I am checking again trying to imitate this in my browser.

**Comment by johannaraisa** [comment]
Very interesting if I change it to labelsClicks.js then it works but not with underscore. Some Apache thing maybe?

**Comment by nugged** [comment]
httpd shouldn't interfere with normal characters and should be ignorant to cases... And it works on my VM, it loads actions and complies the script (console is silent about errors)

Which browser is that as well?

image

it just (by logic) should work for both labelsClicks.js and labels_clicks.js, but seems labelsClicks.js fresh one so it worked and labels_clicks.js somehow precached or reference to it

but: can you try with normal labels_clicks.js in another browser?

Let's try to find the case because of course, this should work.

**Comment by johannaraisa** [comment]
I figure it out for some reason httpd config hand weird row, RewriteRule ^(.*)_(.*).js$ $1.js [N,L]
Don't really know why it is there since the original is this one RewriteRule ^(.*)_[0-9]{2}\.[0-9]{7}\.(js|css)$ $1.$2 [L]

**Comment by johannaraisa** [comment]
Haha, even found the original commit. https://github.com/KohaSuomi/Koha/commit/1c4c5794c4edd3f8d0998e4ff445ed0b4217ce96
Doesn't make sense to me! :D

**Comment by nugged** [comment]
okay, good you found that

**Comment by nugged** [comment]
can I re-commit with labelsClicks.js ?

**Comment by johannaraisa** [comment]
No need since the problem is on our Apache config, I will fix that :)

**Comment by nugged** [comment]
> I figure it out for some reason httpd config hand weird row, RewriteRule ^(.)_(.).js$

this is some "cache" goals, like having a version in file name or date/time, but rewrite to a non-versioned file name, 

a good example of how very wide clauses covering too much in regex makes them universal and name-killers for those who don't know these caveats and using filenames with underscores because "it's allowed in normal life" :),


so it works. Good, then I am back to that other "half items" and "additems speed optimization" fixes I am doing now. 

👍

**Comment by nugged** [comment]
note for future readers: you are reading duplicated/not used PR, real used pull request is this one: https://github.com/KohaSuomi/Koha/pull/109

**Pull request closed without merging**
