### PR TITLE
Hamk postfixes

### PR DESCRIPTION
**Pull request by kivilahtio**

### CODE REVIEW

**Comment by kohaputti** [comment]
" KD-1645 - Koha database autoinstaller and updater - Fix missing newline" should probably be squashed to something in the next rebase?

**Comment by kivilahtio** [comment]
Yes, that would be ideal.

**Comment by kohaputti** [comment]
Can you add (squashable) in the title?

**Comment by kivilahtio** [comment]
Squashme added.

**Comment by kohaputti** [comment]
Can you put actually "KD-1159-4 - (squashable) ..." so it can be found with search from the git logs when doing the squashing and rebase? I can only see one earlier usage of squashme in history which shouldn't probably exists there.

**Comment by kivilahtio** [comment]
What seems to be the problem?
image

**Comment by kohaputti** [comment]
Nobody knows that there is this commit that needs to be squashed because all the other commits use the string (squashable) in the title.

**Comment by kivilahtio** [comment]
Oh, looks like Koha-Suomi has adopted a policy of using
KD-3172 - (squashable)

It used to be postfixed [sS]quash-something
New patches provided.

**Comment by johannaraisa** [comment]
This seems ok now. Shall be merged then.

**Pull request merged**
