### PR TITLE
Elasticsearch backports

### PR DESCRIPTION
**Pull request by kohaputti**
This pull request brings the latest patches related to Elasticsearch support from community version. Please review the commit "Bug 18316: Update schema" (8c2ffeca17d8e7149e63ebe119e2cafcb02e927a) since I did that myself to update the Koha Schema. I didn't want to take the community release manager's similar patch because it had also the database updates (and here we don't need it because we use the atomicupdate).

### CODE REVIEW

**Comment by kivilahtio** [comment]
If the attached test cases pass. It is fine by me.
After a brief overview, tests doesn't seem to test if the indexed record is as expected and if the search results are actually even MARC, or have the desired fields.
But it would be too much to ask it from this PR, the problem is upstream.

**Comment by kohaputti** [comment]
All the attached tests pass expect I couldn't verify t/db_dependent/www/search_utf8.t because we don't have Zebra set up.

**Comment by kivilahtio** [comment]
https://tenor.com/view/thesimpsons-mr-burns-evil-laugh-evillaugh-gif-4076853

**Comment by johannaraisa** [comment]
So is the atomicupdate for "Bug 18316: Update schema" in some other commit?

**Comment by kohaputti** [comment]
It was in a community version but since they are going with their own schema and updatedatabase.pl file versions we cannot just cherry-pick it because the two versions are not compatible. Therefore I decided to create a new commit.

**Comment by kohaputti** [comment]
aah, I understood you wrong. The atomicupdate is in https://github.com/KohaSuomi/Koha/pull/57/commits/561a5fe8ef8e3507516195089988725c83d775f0

**Comment by kivilahtio** [comment]
The community atomicupdates are compatible?
If they are not, then atomicupdater needs to be fixed.

**Comment by kohaputti** [comment]
The community atomicupdate I cherry-picked is compatible.

**Comment by kivilahtio** [comment]
I think I misunderstood a bit what you were discussing about.

**Comment by kohaputti** [comment]
Yes, I was referring to the community *commit* being incompatible with our schema and updatedatabase.pl version. Not that the actual files couldn't be merged but then the community commit would have to be changed a quite a lot so I thought it would be more truthful to just create a new commit because if I cherry-picked & fixed the conlfict the cherry-picked commit wouldn't be the anything like the original, plus solving the conflict is probably not worth the effort.

**Pull request merged**
