### PR TITLE
KD-1902: (squashable) Add basepath to example link

### PR DESCRIPTION
**Pull request by taskula**
See c35a49144fc958fafa111f1372f70d0e5aa525c1

Just adds the same functionality to another link as here:
https://github.com/KohaSuomi/Koha/commit/c35a49144fc958fafa111f1372f70d0e5aa525c1#diff-07d79c86d682827b2ed2e3d6c534c74bR141

### CODE REVIEW

**Comment by kohaputti** [comment]
At least for my koha setup this doesn't work. The link "https://xxxx.fi/cgi-bin/koha/tools/static_content/claiming/example/pdfbill.docx" says not found / 404.

**Comment by taskula** [comment]
> At least for my koha setup this doesn't work. The link "https://xxxx.fi/cgi-bin/koha/tools/static_content/claiming/example/pdfbill.docx" says not found / 404.

How does your koha-conf.xml & koha-httpd.conf look like? Test cases:
- billingSetup->basePath empty, no apache restrictions (should always work)
- billingSetup->basePath empty, koha-tmpl/static_content/claiming restricted by apache (returns 401)
- billingSetup->basePath https://username:password@xxx.fi/, koha-tmpl/static_content/claiming restricted by apache

Example koha-httpd digest auth

```
   <Directory /home/koha/Koha/koha-tmpl/static_content/claiming/>
      AuthType Digest
      AuthName "lasku"
      AuthUserFile /home/koha/koha-dev/etc/digests/lasku
      AllowOverride None
      Require valid-user
      Options Indexes
   </Directory>
```

**Comment by taskula** [comment]
> At least for my koha setup this doesn't work. The link "https://xxxx.fi/cgi-bin/koha/tools/static_content/claiming/example/pdfbill.docx" says not found / 404.

The link is wrong. It shouldn't have cgi-bin/koha/tools in it but instead just /static_content/claiming/example/pdfbill.docx

See https://github.com/KohaSuomi/Koha/commit/c35a49144fc958fafa111f1372f70d0e5aa525c1#diff-d14b3804108e4704f149a653657e6ab5R96

This should add '/' if your basePath is empty, right?

**Comment by kohaputti** [comment]
@taskula all good with this, I was missing the c35a491 commit.

**Pull request merged**
