### PR TITLE
Bug 24101: On-site checkouts to circulation rules

### PR DESCRIPTION
**Pull request by taskula**
This feature is a backport of [Bug 24101](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=24101) and its dependencies.

Here in Koha-Suomi, it replaces issuingrules.circulation_level with issuingrules.checkout_type. The checkout_type is bound to issues.checkout_type and there are currently two possible values, CHECKOUT and ONSITE. A librarian can then distinguish circulation rules between normal and on-site checkouts.

This feature was sponsored by The National Library of Finland as well as requested to be backported into Koha-Suomi.

Sponsored by: The National Library of Finland

### CODE REVIEW

**Comment by taskula** [comment]
Some commits are still missing tests, and some unit tests are still failing. But the basic functionality is now testable via Koha staff client.

**Comment by taskula** [comment]
You will observe the following unit test failures that are not caused by this PR:

1. t/db_dependent/Circulation.t

>
    #   Failed test 'Can auto renew, OPACFineNoRenewals=10, patron has 10'
    #   at t/db_dependent/Circulation.t line 678.
    #          got: 'auto_too_much_oweing'
    #     expected: 'auto_renew'
    # Looks like you failed 1 test of 6.

Resolution: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=18802

**Comment by taskula** [comment]
In order to ease NatLibFi's path of moving closer to upstream Koha, we have decided to remove atomicupdates of Bug 25037 and commits dependent on that. Less database updates, easier the migration.

Now issues.onsite_checkout remains as it is (0 or 1), but issuingrules.checkout_type is still using "CHECKOUT" and "ONSITE" keywords.

**Comment by taskula** [comment]
I will squash and tidy the patches once @NatLibFi 's librarians have tested the feature. So please do not review the code carefully yet.

**Comment by taskula** [comment]
Ready for review.

**Comment by kohaputti** [comment]
The commits "Bug 24101: Calculate on-site checkouts due date via circulation rules" and  "Bug 24101: Enable renewals for on-site checkouts " might be something that requires a syspref at least in community. I have reviewed now the pull request and it looks good at least for our use case. Did anybody else using Koha-Suomi Koha want this feature? If not we probably don't want to merge this to Koha-Suomi codebase given it is a massive change and we will not be needing this in few months since the plan is to use the community version where this will have been hopefully implemented by then. So I suggest we keep this pull request here like this, so that it is at least preserved in somewhere in case someone else besides us wants to use it, or add a new branch to the Koha repo here for this feature only.

**Review by ghost — APPROVED** [review]

**Comment by taskula** [comment]
> The commits "Bug 24101: Calculate on-site checkouts due date via circulation rules" and "Bug 24101: Enable renewals for on-site checkouts " might be something that requires a syspref at least in community.

My idea was that it would be controlled via OnSiteCheckouts syspref and if enabled, then only the circulation rules. The default behavior would be as it is right now (due date at the end of today) and not renewable. If OnSiteCheckouts syspref is not enabled, we could hide it all together from the circulation rules user interface and just stick to the defaults. But this is something that I still have to work on.

But the complexity of this feature is growing more and more annoyance in me. I'm somewhat pessimistic that this change can advance the way it is in this PR (as well as the patches in Bugzilla as of now) in upstream. As you said, the change is pretty massive. It makes little sense to update every occurrence of get/set_circulation_rules method with every new scope that we might ever add in the future.

It's a rebase hell and adds a high chance for regression.

Instead we should rethink the whole process of matching libraries, items and patrons to circulation rules.

One idea was to refactor get_effective_circulation_rule(s) methods in a way that allows us to use all properties of Koha::Item/Patron/Library objects. So we would simply pass all the available information (i.e. a Koha::Item/Patron/Library object/hashref) to the subroutine and it would handle the matching of object's properties to a circulation rule.

But that will also be a massive change. And it does not really help with onsite_checkout because it is not a property of Koha::Item. And this is not really in the scope of this assignment anymore.

Perhaps you have some ideas how this feature could be better introduced to the Koha community?

> Did anybody else using Koha-Suomi Koha want this feature? 

No. As far as I understood, they are against any new features until the version has been changed. Which seems reasonable.

> If not we probably don't want to merge this to Koha-Suomi codebase given it is a massive change and we will not be needing this in few months since the plan is to use the community version where this will have been hopefully implemented by then. So I suggest we keep this pull request here like this, so that it is at least preserved in somewhere in case someone else besides us wants to use it, or add a new branch to the Koha repo here for this feature only.

In that case we can close it. You can just grab the commits into your branch.

**Pull request closed without merging**
