### PR TITLE
KD-1886: (squashable) File name case fix

### PR DESCRIPTION
**Pull request by nugged**
There are two same modules in the repo. One occasionally went with lowercase 'item':

'Koha/Reporting/Report/Oma/CollectionByBiblioitem.pm'
'Koha/Reporting/Report/Oma/CollectionByBiblioItem.pm'

and, btw, files differ by contents, not entirely, but slightly.

Lowercase named module ('item') not referred and not used anywhere in the code.

CollectionByBiblioItem.pm referred and used in Koha/Reporting/Report/Factory.pm

Also, this file name case difference makes git emitting warnings on a case insensitive
file systems and breaks the repository just out of the box.

This casing of course not the Ubuntu related case but there are no such errors, for example in Koha Community version and generally bad practice.

### CODE REVIEW

**Comment by kohaputti** [comment]
Fix the commit titles to be in the format "KD-1886: (squashable) XXXX". @janPasi can probably review rest of this since he worked on this part of the report module?

**Comment by janPasi** [comment]
That's weird indeed. I'll look into this to identify the correct one before merging your pull request.

**Comment by taskula** [comment]
Confirming this file is not referred anywhere in Koha source.

**Comment by kohaputti** [comment]
I probably can go ahead with pushing this change since @taskula says the file is not used, and if there is something in this file that is deleted now you can transfer the code to the other file later.

**Comment by janPasi** [comment]
People at PiiMega (the developer of the reporting tool) think the other file got there by mistake. It seems that it has been with us from the early days of the development of the reporting tool, from the year 2017. Like @taskula pointed out, it's not really used, at least in the present version. I was just wondering on whether it perhaps contains some early-days fixes that we need, but maybe not. Since PiiMega doesn't remember why it's there, it's probably safe to get rid of it.

**Pull request merged**
