### PR TITLE
KD-3404: (squashable) check in without log in

### PR DESCRIPTION
**Pull request by juhak18**
Corections to template sco-main

### CODE REVIEW

**Comment by kohaputti** [comment]
why not do the backport @taskula suggested in https://github.com/KohaSuomi/Koha/pull/142 ?

**Comment by AnneliO** [comment]
I tested the community's version and it does not do everything we need it to do. It does not handle reserves as our version. When you check in a reserved item the reserve is not handled and we want it to do that. Our version also follows the system preference "RequireSCCheckInBeforeNotifyingPickups" .

The user interface is too complicated for children who mainly use it. Check in and check out are two different pages. When you return items, you first read the barcodes with a barcode reader. Then you have to click with a mouse "check in". After that you get a page where the system tells which items were checked in and which ones were not checked in (not checked out or unknown barcode). System also doesn't tell the user the titles of items checked in, it only shows you the barcode. Finally you have to click again with a mouse "Finish"-button.

In our version there is only one page with two boxes. When checking in you just click once on the check in box and read items barcode with barcode reader. And that's it. The page reloads automatically and the item checked in previously disappears from the screen. Only the title and barcode of the last item checked in is shown.

**Comment by kohaputti** [comment]
The reserve handling missing is in community version is a bug and should be fixed. So then we are left with the cumbersome UI in the community version, why not fix that too? if you really want to do your own check-in module have you considered building something on top of the REST API or SIP2 API so we don't have to maintain it in Koha code and make the community upgrades a lot harder?

**Comment by AnneliO** [comment]
In the long term we agree that we should go to the community version and develop that further but we need this now and cannot wait for all the changes to be implemented to the community. This has to be functional at the beginning of the January 2020.

**Comment by kohaputti** [comment]
Ok, let's merge this then. And I hope the long term is sooner and not later.

**Pull request merged**
